/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedGiocaRouteImport } from './routes/_authenticated/gioca'
import { Route as AuthenticatedMissioniRouteImport } from './routes/_authenticated/missioni'
import { Route as AuthenticatedProfiloRouteImport } from './routes/_authenticated/profilo'
import { Route as AuthenticatedShopRouteImport } from './routes/_authenticated/shop'
import { Route as ApiPublicHooksAdRewardRouteImport } from './routes/api/public/hooks/ad-reward'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGiocaRoute = AuthenticatedGiocaRouteImport.update({
  id: '/gioca',
  path: '/gioca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMissioniRoute = AuthenticatedMissioniRouteImport.update({
  id: '/missioni',
  path: '/missioni',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfiloRoute = AuthenticatedProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopRoute = AuthenticatedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksAdRewardRoute = ApiPublicHooksAdRewardRouteImport.update({
  id: '/api/public/hooks/ad-reward',
  path: '/api/public/hooks/ad-reward',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRoute
  '/gioca': typeof AuthenticatedGiocaRoute
  '/missioni': typeof AuthenticatedMissioniRoute
  '/profilo': typeof AuthenticatedProfiloRoute
  '/shop': typeof AuthenticatedShopRoute
  '/api/public/hooks/ad-reward': typeof ApiPublicHooksAdRewardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRoute
  '/gioca': typeof AuthenticatedGiocaRoute
  '/missioni': typeof AuthenticatedMissioniRoute
  '/profilo': typeof AuthenticatedProfiloRoute
  '/shop': typeof AuthenticatedShopRoute
  '/api/public/hooks/ad-reward': typeof ApiPublicHooksAdRewardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/gioca': typeof AuthenticatedGiocaRoute
  '/_authenticated/missioni': typeof AuthenticatedMissioniRoute
  '/_authenticated/profilo': typeof AuthenticatedProfiloRoute
  '/_authenticated/shop': typeof AuthenticatedShopRoute
  '/api/public/hooks/ad-reward': typeof ApiPublicHooksAdRewardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/chat'
    | '/gioca'
    | '/missioni'
    | '/profilo'
    | '/shop'
    | '/api/public/hooks/ad-reward'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/chat'
    | '/gioca'
    | '/missioni'
    | '/profilo'
    | '/shop'
    | '/api/public/hooks/ad-reward'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/chat'
    | '/_authenticated/gioca'
    | '/_authenticated/missioni'
    | '/_authenticated/profilo'
    | '/_authenticated/shop'
    | '/api/public/hooks/ad-reward'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksAdRewardRoute: typeof ApiPublicHooksAdRewardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gioca': {
      id: '/_authenticated/gioca'
      path: '/gioca'
      fullPath: '/gioca'
      preLoaderRoute: typeof AuthenticatedGiocaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missioni': {
      id: '/_authenticated/missioni'
      path: '/missioni'
      fullPath: '/missioni'
      preLoaderRoute: typeof AuthenticatedMissioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profilo': {
      id: '/_authenticated/profilo'
      path: '/profilo'
      fullPath: '/profilo'
      preLoaderRoute: typeof AuthenticatedProfiloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop': {
      id: '/_authenticated/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthenticatedShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/ad-reward': {
      id: '/api/public/hooks/ad-reward'
      path: '/api/public/hooks/ad-reward'
      fullPath: '/api/public/hooks/ad-reward'
      preLoaderRoute: typeof ApiPublicHooksAdRewardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedGiocaRoute: typeof AuthenticatedGiocaRoute
  AuthenticatedMissioniRoute: typeof AuthenticatedMissioniRoute
  AuthenticatedProfiloRoute: typeof AuthenticatedProfiloRoute
  AuthenticatedShopRoute: typeof AuthenticatedShopRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedGiocaRoute: AuthenticatedGiocaRoute,
  AuthenticatedMissioniRoute: AuthenticatedMissioniRoute,
  AuthenticatedProfiloRoute: AuthenticatedProfiloRoute,
  AuthenticatedShopRoute: AuthenticatedShopRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksAdRewardRoute: ApiPublicHooksAdRewardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
