/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedGiocaRouteImport } from './routes/_authenticated/gioca'
import { Route as AuthenticatedMissioniRouteImport } from './routes/_authenticated/missioni'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGiocaRoute = AuthenticatedGiocaRouteImport.update({
  id: '/gioca',
  path: '/gioca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMissioniRoute = AuthenticatedMissioniRouteImport.update({
  id: '/missioni',
  path: '/missioni',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gioca': typeof AuthenticatedGiocaRoute
  '/missioni': typeof AuthenticatedMissioniRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gioca': typeof AuthenticatedGiocaRoute
  '/missioni': typeof AuthenticatedMissioniRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/gioca': typeof AuthenticatedGiocaRoute
  '/_authenticated/missioni': typeof AuthenticatedMissioniRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/gioca' | '/missioni'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/gioca' | '/missioni'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/gioca'
    | '/_authenticated/missioni'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gioca': {
      id: '/_authenticated/gioca'
      path: '/gioca'
      fullPath: '/gioca'
      preLoaderRoute: typeof AuthenticatedGiocaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missioni': {
      id: '/_authenticated/missioni'
      path: '/missioni'
      fullPath: '/missioni'
      preLoaderRoute: typeof AuthenticatedMissioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGiocaRoute: typeof AuthenticatedGiocaRoute
  AuthenticatedMissioniRoute: typeof AuthenticatedMissioniRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGiocaRoute: AuthenticatedGiocaRoute,
  AuthenticatedMissioniRoute: AuthenticatedMissioniRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
