REVOKE ALL ON FUNCTION public.team_leaderboard() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_get_automation() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_set_automation(boolean, time, integer, boolean, boolean, jsonb) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_run_automation() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_delete_shop_item(text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_upsert_shop_item(text, text, text, text, integer, integer, integer, boolean, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_set_week(date, text, text, text, text, timestamptz, timestamptz, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.get_state() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.draw_quiz() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.answer_quiz(integer, integer) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.buy_item(text, uuid[]) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.settle_week(date) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.bootstrap_player(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.team_leaderboard() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_get_automation() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_automation(boolean, time, integer, boolean, boolean, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_run_automation() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_delete_shop_item(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_upsert_shop_item(text, text, text, text, integer, integer, integer, boolean, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_week(date, text, text, text, text, timestamptz, timestamptz, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_state() TO authenticated;
GRANT EXECUTE ON FUNCTION public.draw_quiz() TO authenticated;
GRANT EXECUTE ON FUNCTION public.answer_quiz(integer, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.buy_item(text, uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.bootstrap_player(text) TO authenticated;